#!/bin/sh

## SekireiTools (https://github.com/yomichi/SekireiTools)
## Copyright (c) Yuichi Motoyama <yomichi@tsg.jp>
## Distributed under the Boost Software License Version 1.0.

script_dir=$(dirname $(readlink -f $0))

if [ -f "${script_dir}/users.txt" ]
then
  USERS=`cat "${script_dir}/users.txt"`
else
  USERS="$USER"
fi

qstat -a | head -n 5
for user in ${USERS}; do
qstat -a -u $user | tail -n +6 | awk '$10 ~ /R/'
qstat -T -u $user | tail -n +7 | awk '$10 !~ /R/'
done
