#!/bin/sh

## SekireiTools (https://github.com/yomichi/SekireiTools)
## Copyright (c) Yuichi Motoyama <yomichi@tsg.jp>
## Distributed under the Boost Software License Version 1.0.

set -ue

usage="usage: `basename $0` (small|middle|large|acc-middle|acc-large|fat|int)"

if [ $# -eq 0 ]; then
qstat -a \
  | gawk 'BEGIN {small=0; middle=0; large=0;
               accmiddle=0; acclarge=0;
               fat=0; interactive=0;
               j_small=0; j_middle=0; j_large=0;
               j_accmiddle=0; j_acclarge=0;
               j_fat=0; j_interactive=0}
        $10 ~ /R/ && $3 ~ /(F|L|B)4cpu/ {small += $6; j_small += 1;}
        $10 ~ /R/ && $3 ~ /(F|L|B)36cpu/ {middle += $6; j_middle += 1;}
        $10 ~ /R/ && $3 ~ /(F|L|B)144cpu/ {large += $6; j_large += 1;}
        $10 ~ /R/ && $3 ~ /(F|L|B)18acc/ {accmiddle += $6; j_accmiddle += 1;}
        $10 ~ /R/ && $3 ~ /(F|L|B)72acc/ {acclarge += $6; j_acclarge += 1;}
        $10 ~ /R/ && $3 ~ /(F|L|B)2fat/ {fat += $6; j_fat += 1;}
        $10 ~ /R/ && $3 ~ /i/ {interactive += $6; j_interactive += 1;}
        END {print "running";
             printf("small      : %4d /  216 nodes ( %3d jobs)\n", small, j_small);
             printf("middle     : %4d /  288 nodes ( %3d jobs)\n", middle, j_middle);
             printf("large      : %4d / 1008 nodes ( %3d jobs)\n", large,  j_large);
             printf("acc-middle : %4d /  108 nodes ( %3d jobs)\n", accmiddle,j_accmiddle);
             printf("acc-large  : %4d /  144 nodes ( %3d jobs)\n", acclarge,j_acclarge);
             printf("fat        : %4d /   17 nodes ( %3d jobs)\n", fat, j_fat);
             printf("int        : %4d /  108 nodes ( %3d jobs)\n", interactive, j_interactive);
           }'
fi

if [ $# -gt 0 ]; then
case "$1" in
  "small" ) qstat -w F4cpu B4cpu L4cpu \
            | gawk 'BEGIN {F=0; B=0; L=0;
                           Fj=0; Bj=0; Lj=0;
                           WF=0; WFj=0;
                           WL=0; WLj=0;
                           WB=0; WBj=0}
    $10 ~ /R/ && $3 ~ /F4cpu/ {F += $6; Fj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1]; 
                               printf "%s F %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /F4cpu/ {WF += $6; WFj += 1}
    $10 ~ /R/ && $3 ~ /B4cpu/ {B += $6; Bj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s B %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /B4cpu/ {WB += $6; WBj += 1}
    $10 ~ /R/ && $3 ~ /L4cpu/ {L += $6; Lj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s L %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /L4cpu/ {WL += $6; WLj += 1}
    END {print ""
         print "running :";
         print "F4cpu   :", F, "nodes /", Fj, "jobs";
         print "L4cpu   :", L, "nodes /", Lj, "jobs";
         print "B4cpu   :", B, "nodes /", Bj, "jobs";
         print "total   :", F+L+B, "/ 216 nodes";
         print ""
         print "waiting :";
         print "F4cpu   :", WF, "nodes /", WFj, "jobs";
         print "L4cpu   :", WL, "nodes /", WLj, "jobs";
         print "B4cpu   :", WB, "nodes /", WBj, "jobs";
         print "total   :", WF+WL+WB, " nodes /", WFj+WLj+WBj, "jobs";
     }';;
  "middle" ) qstat -w F36cpu B36cpu L36cpu \
            | gawk 'BEGIN {F=0; B=0; L=0;
                           Fj=0; Bj=0; Lj=0;
                           WF=0; WFj=0;
                           WL=0; WLj=0;
                           WB=0; WBj=0}
    $10 ~ /R/ && $3 ~ /F36cpu/ {F += $6; Fj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s F %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /F36cpu/ {WF += $6; WFj += 1}
    $10 ~ /R/ && $3 ~ /B36cpu/ {B += $6; Bj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s B %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /B36cpu/ {WB += $6; WBj += 1}
    $10 ~ /R/ && $3 ~ /L36cpu/ {L += $6; Lj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s L %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /L36cpu/ {WL += $6; WLj += 1}
    END {print ""
         print "running :";
         print "F36cpu  :", F, "nodes /", Fj, "jobs";
         print "L36cpu  :", L, "nodes /", Lj, "jobs";
         print "B36cpu  :", B, "nodes /", Bj, "jobs";
         print "total   :", F+L+B, "/ 288 nodes";
         print ""
         print "waiting :";
         print "F36cpu  :", WF, "nodes /", WFj, "jobs";
         print "L36cpu  :", WL, "nodes /", WLj, "jobs";
         print "B36cpu  :", WB, "nodes /", WBj, "jobs";
         print "total   :", WF+WL+WB, " nodes /", WFj+WLj+WBj, "jobs";
     }';;
  "large" ) qstat -w F144cpu B144cpu L144cpu \
            | gawk 'BEGIN {F=0; B=0; L=0;
                           Fj=0; Bj=0; Lj=0;
                           WF=0; WFj=0;
                           WL=0; WLj=0;
                           WB=0; WBj=0}
    $10 ~ /R/ && $3 ~ /F144cpu/ {F += $6; Fj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s F %15s %3snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /F144cpu/ {WF += $6; WFj += 1}
    $10 ~ /R/ && $3 ~ /B144cpu/ {B += $6; Bj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s B %15s %3snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /B144cpu/ {WB += $6; WBj += 1}
    $10 ~ /R/ && $3 ~ /L144cpu/ {L += $6; Lj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s L %15s %3snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /L144cpu/ {WL += $6; WLj += 1}
    END {print ""
         print "running :";
         print "F144cpu :", F, "nodes /", Fj, "jobs";
         print "L144cpu :", L, "nodes /", Lj, "jobs";
         print "B144cpu :", B, "nodes /", Bj, "jobs";
         print "total   :", F+L+B, "/ 1008 nodes";
         print ""
         print "waiting :";
         print "F144cpu :", WF, "nodes /", WFj, "jobs";
         print "L144cpu :", WL, "nodes /", WLj, "jobs";
         print "B144cpu :", WB, "nodes /", WBj, "jobs";
         print "total   :", WF+WL+WB, " nodes /", WFj+WLj+WBj, "jobs";
    }';;
  "acc-middle" ) qstat -w F18acc B18acc L18acc \
            | gawk 'BEGIN {F=0; B=0; L=0;
                           Fj=0; Bj=0; Lj=0;
                           WF=0; WFj=0;
                           WL=0; WLj=0;
                           WB=0; WBj=0}
    $10 ~ /R/ && $3 ~ /F18acc/ {F += $6; Fj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s F %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /F18acc/ {WF += $6; WFj += 1}
    $10 ~ /R/ && $3 ~ /B18acc/ {B += $6; Bj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s B %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /B18acc/ {WB += $6; WBj += 1}
    $10 ~ /R/ && $3 ~ /L18acc/ {L += $6; Lj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s L %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /L18acc/ {WL += $6; WLj += 1}
    END {print ""
         print "running :";
         print "F18acc  :", F, "nodes /", Fj, "jobs";
         print "L18acc  :", L, "nodes /", Lj, "jobs";
         print "B18acc  :", B, "nodes /", Bj, "jobs";
         print "total   :", F+L+B, "/ 108 nodes";
         print ""
         print "waiting :";
         print "F18acc  :", WF, "nodes /", WFj, "jobs";
         print "L18acc  :", WL, "nodes /", WLj, "jobs";
         print "B18acc  :", WB, "nodes /", WBj, "jobs";
         print "total   :", WF+WL+WB, " nodes /", WFj+WLj+WBj, "jobs";
    }';;
  "acc-large" ) qstat -w F72acc B72acc L72acc \
            | gawk 'BEGIN {F=0; B=0; L=0;
                           Fj=0; Bj=0; Lj=0;
                           WF=0; WFj=0;
                           WL=0; WLj=0;
                           WB=0; WBj=0}
    $10 ~ /R/ && $3 ~ /F72acc/ {F += $6; Fj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s F %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /F72acc/ {WF += $6; WFj += 1}
    $10 ~ /R/ && $3 ~ /B72acc/ {B += $6; Bj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s B %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /B72acc/ {WB += $6; WBj += 1}
    $10 ~ /R/ && $3 ~ /L72acc/ {L += $6; Lj +=1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s L %15s %2snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /L72acc/ {WL += $6; WLj += 1}
    END {print ""
         print "running :";
         print "F72acc  :", F, "nodes /", Fj, "jobs";
         print "B72acc  :", B, "nodes /", Bj, "jobs";
         print "total   :", F+L+B, "/ 144 nodes";
         print ""
         print "waiting :";
         print "F72acc  :", WF, "nodes /", WFj, "jobs";
         print "B72acc  :", WB, "nodes /", WBj, "jobs";
         print "total   :", WF+WL+WB, " nodes /", WFj+WLj+WBj, "jobs";
     }';;
  "fat" ) qstat -w F2fat B2fat L2fat \
            | gawk 'BEGIN {F=0; B=0; L=0;
                           Fj=0; Bj=0; Lj=0;
                           WF=0; WFj=0;
                           WL=0; WLj=0;
                           WB=0; WBj=0}
    $10 ~ /R/ && $3 ~ /F2fat/ {F += $6; Fj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s F %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /F2fat/ {WF += $6; WFj += 1}
    $10 ~ /R/ && $3 ~ /B2fat/ {B += $6; Bj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s B %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /B2fat/ {WB += $6; WBj += 1}
    $10 ~ /R/ && $3 ~ /L2fat/ {L += $6; Lj += 1;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s L %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 !~ /R/ && $3 ~ /L2fat/ {WL += $6; WLj += 1}
    END {print ""
        print "running :";
        print "F2fat   :", F, "nodes /", Fj, "jobs";
        print "B2fat   :", B, "nodes /", Bj, "jobs";
        print "L2fat   :", L, "nodes /", Lj, "jobs";
        print "total   :", F+L+B, "/ 17 nodes";
        print ""
        print "waiting :";
        print "F2fat   :", WF, "nodes /", WFj, "jobs";
        print "B2fat   :", WB, "nodes /", WBj, "jobs";
        print "L2fat   :", WL, "nodes /", WLj, "jobs";
        print "total   :", WF+WL+WB, " nodes /", WFj+WLj+WBj, "jobs";
    }';;
  "int" ) qstat -w i18cpu i9acc i1fat \
            | gawk 'BEGIN {C=0; A=0; F=0; Wnode=0; Wjob=0;}
    $10 ~ /R/ && $3 ~ /i18cpu/ {C += $6;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s cpu %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 ~ /R/ && $3 ~ /i9acc/ {A += $6;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s acc %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 ~ /R/ && $3 ~ /i1fat/ {F += $6;
                               cmd="username "$2; cmd | getline name; close(cmd);
                               split($1,a,/\./); jobid = a[1];
                               printf "%s fat %15s %snodes %s/%s %s\n", jobid, $4, $6, $11, $9, name}
    $10 ~ /(Q|H)/ {Wnode += $6; Wjob+=1}
    END {print "i18cpu  :", C, "/ 72";
         print "i9acc   :", A, "/ 36";
         print "i1fat   :", F, "/ 2";
         print "waiting :", Wnode, "nodes / ", Wjob, "jobs";
     }';;
  * ) echo $usage; exit -1;;
esac
fi
