#!/bin/sh
usage="usage: $(basename $(readlink -f $0)) [--queue=(cpu|acc|fat)] [--omp=NUM_OPENMP] [--dry] [NUM_NODE]"

nnodes=1
nprocs=1
nthreads=24
queue="cpu"
dryrun=""

for arg in $@; do
    check_omp=""
    check_omp=${arg#--omp=}
    check_queue=""
    check_queue=${arg#--queue=}
    if [ "$check_omp" != "$arg" ]; then
        if [ "_`echo $check_omp | grep -E '^[0-9]+$'`" == "_" ]; then
            echo $usage
            exit 64
        fi
        nthreads=$check_omp
    elif [ "$check_queue" != "$arg" ]; then
        if [ "_`echo $check_queue | grep -E '(cpu|acc|fat)'`" == "_" ]; then
            echo $usage
            exit 64
        fi
        queue=$check_queue
    elif [ "$arg" == "--dry" ]; then
        dryrun=1
    elif [ "_`echo $arg | grep -E '^[0-9]+$'`" == "_" ]; then
        echo $usage
        exit 64
    else
        nnodes=$arg
    fi
done

case $nthreads in
    1  ) nprocs=`echo 24 \* $nnodes | bc -l` ;;
    2  ) nprocs=`echo 12 \* $nnodes | bc -l` ;;
    3  ) nprocs=`echo 8 \* $nnodes | bc -l` ;;
    4  ) nprocs=`echo 6 \* $nnodes | bc -l` ;;
    6  ) nprocs=`echo 4 \* $nnodes | bc -l` ;;
    8  ) nprocs=`echo 3 \* $nnodes | bc -l` ;;
    12 ) nprocs=`echo 2 \* $nnodes | bc -l` ;;
    24 ) nprocs=`echo 1 \* $nnodes | bc -l` ;;
    *  ) echo "Invalid input: --omp=<NUM_OPENMP> should be divisor of 24."; exit 64;; 
esac

case $queue in
    "cpu" ) queue=i18cpu;;
    "acc" ) queue=i9acc;;
    "fat" ) queue=i1fat;;
    *) echo $usage && exit 64;;
esac

if [ "$dryrun" == "1" ]; then
    echo "qsub -queue $queue -node $nnodes -mpi $nprocs -omp $nthreads -I"
else
    /opt/pbs/issp/bin/qsub -queue $queue -node $nnodes -mpi $nprocs -omp $nthreads -I
fi
