#!/bin/sh
usage="usage: $0 [--mpi=NUM_MPI] [--omp=NUM_OPENMP] [--dry] [NUM_NODE]"

nnodes=""
nprocs=""
nthreads=""
dryrun=""

for arg in $@; do
    check_mpi=""
    check_mpi=${arg#--mpi=}
    check_omp=""
    check_omp=${arg#--omp=}
    if [ "$check_mpi" != "$arg" ]; then
        if [ "_`echo $check_mpi | grep -E '^[0-9]+$'`" == "_" ]; then
            echo $usage
            exit 127
        fi
        nprocs=$check_mpi
    elif [ "$check_omp" != "$arg" ]; then
        if [ "_`echo $check_omp | grep -E '^[0-9]+$'`" == "_" ]; then
            echo $usage
            exit 127
        fi
        nthreads=$check_omp
    elif [ "$arg" == "--dry" ]; then
        dryrun=1
    elif [ "_`echo $arg | grep -E '^[0-9]+$'`" == "_" ]; then
        echo $usage
        exit 127
    else
        nnodes=$arg
    fi
done

if [ "_$nnodes" == "_" ] ; then
    nnodes=1
fi

if [ "_$nprocs" == "_" ] ; then
    nprocs=$nnodes
fi

if [ "_$nthreads" == "_" ] ; then
    procs_per_node=`echo $nprocs / $nnodes | bc -l`
    nthreads=`echo 24 / $procs_per_node | bc`
fi

script_dir=$(dirname $(readlink -f $0))
if [ "$dryrun" == "1" ]; then
    echo "qsub -node $nnodes -mpi $nprocs -omp $nthreads $script_dir/interactive.sh"
else
    qsub -node $nnodes -mpi $nprocs -omp $nthreads $script_dir/interactive.sh
fi
